name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
      - develop
      - master
jobs:
  checkout:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MAIN_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm build
      - name: List directories
        run: ls 
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: build

