name: Dev Build and Deploy

on:
  push:
    branches:
      - main
      - master
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      
      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: yarn build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./build
